"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class SyncBagCtrl(object):
    __slots__ = ["cmd", "start_t", "duration", "rate", "system_time", "token"]

    __typenames__ = ["int32_t", "float", "float", "float", "double", "int32_t"]

    __dimensions__ = [None, None, None, None, None, None]

    def __init__(self):
        self.cmd = 0
        self.start_t = 0.0
        self.duration = 0.0
        self.rate = 0.0
        self.system_time = 0.0
        self.token = 0

    def encode(self):
        buf = BytesIO()
        buf.write(SyncBagCtrl._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ifffdi", self.cmd, self.start_t, self.duration, self.rate, self.system_time, self.token))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != SyncBagCtrl._get_packed_fingerprint():
            raise ValueError("Decode error")
        return SyncBagCtrl._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = SyncBagCtrl()
        self.cmd, self.start_t, self.duration, self.rate, self.system_time, self.token = struct.unpack(">ifffdi", buf.read(28))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if SyncBagCtrl in parents: return 0
        tmphash = (0xfbc9176aeaf6146) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if SyncBagCtrl._packed_fingerprint is None:
            SyncBagCtrl._packed_fingerprint = struct.pack(">Q", SyncBagCtrl._get_hash_recursive([]))
        return SyncBagCtrl._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", SyncBagCtrl._get_packed_fingerprint())[0]

