"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class TimeSync(object):
    __slots__ = ["drone_id", "system_time0", "bag_time0", "token"]

    __typenames__ = ["int32_t", "double", "double", "int32_t"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.drone_id = 0
        self.system_time0 = 0.0
        self.bag_time0 = 0.0
        self.token = 0

    def encode(self):
        buf = BytesIO()
        buf.write(TimeSync._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">iddi", self.drone_id, self.system_time0, self.bag_time0, self.token))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != TimeSync._get_packed_fingerprint():
            raise ValueError("Decode error")
        return TimeSync._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = TimeSync()
        self.drone_id, self.system_time0, self.bag_time0, self.token = struct.unpack(">iddi", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if TimeSync in parents: return 0
        tmphash = (0xa2675080f628d6b5) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if TimeSync._packed_fingerprint is None:
            TimeSync._packed_fingerprint = struct.pack(">Q", TimeSync._get_hash_recursive([]))
        return TimeSync._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", TimeSync._get_packed_fingerprint())[0]

