"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class TimeSync(object):
    __slots__ = ["system_time", "played_time_sys", "played_time_bag", "rate"]

    __typenames__ = ["double", "double", "double", "double"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.system_time = 0.0
        self.played_time_sys = 0.0
        self.played_time_bag = 0.0
        self.rate = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(TimeSync._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">dddd", self.system_time, self.played_time_sys, self.played_time_bag, self.rate))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != TimeSync._get_packed_fingerprint():
            raise ValueError("Decode error")
        return TimeSync._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = TimeSync()
        self.system_time, self.played_time_sys, self.played_time_bag, self.rate = struct.unpack(">dddd", buf.read(32))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if TimeSync in parents: return 0
        tmphash = (0x3b471198f97890d6) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if TimeSync._packed_fingerprint is None:
            TimeSync._packed_fingerprint = struct.pack(">Q", TimeSync._get_hash_recursive([]))
        return TimeSync._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", TimeSync._get_packed_fingerprint())[0]

